#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <commctrl.h>
#include <commdlg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <time.h>
#include "stnc_gui.h"
#include "stnc_client.h"

#define UPDATED (WM_APP+1)
#define STOPPED (WM_APP+2)
enum { NAV=100,REFRESH=101,CREATE_WALLET=102,CREATE_IDENTITY=103,SEND=104,DESTINATION=105,AMOUNT=106,
 MINING_ON=107,MINING_OFF=108,CPU=109,CPU_SAVE=110,COPY_ADDRESS=111,CREATE_CONTRACT=112,
 CONTRACT_TYPE=113,CONTRACT_TERMS=114,CONTRACT_RESULT=115 };
enum { B_OVERVIEW=300,B_SEND,B_RECEIVE,B_WALLET,B_CONTRACTS,B_ACTIVITY };
enum { M_EXIT=2000,M_WALLET_ADDRESS,M_WALLET_IDENTITY,M_WALLET_CONTRACT,M_SEND,M_RECEIVE,M_CONTRACTS,M_ACTIVITY,M_MINING,M_ABOUT };
enum { P_OVERVIEW,P_SEND,P_RECEIVE,P_WALLET_ADDRESS,P_WALLET_IDENTITY,P_WALLET_CONTRACT,P_CONTRACTS,P_ACTIVITY,P_MINING,P_COUNT };
typedef struct page_control { HWND h; int page; } page_control;
static struct {
 HWND w,title,content,sync,progress; HWND nav[6]; HFONT normal,bold,titlefont,navfont;
 page_control pc[32]; size_t pc_count; CRITICAL_SECTION lock; HANDLE wake,thread; volatile LONG stopping;
 int ready,busy,failed,page; stnc_client_request *pending; stnc_client_snapshot snap; char message[4096];
} ui;
static HWND ctl(const char *c,const char *t,DWORD s,int id,int page,int x,int y,int w,int h)
{ HWND z=CreateWindowExA(strcmp(c,"EDIT")==0?WS_EX_CLIENTEDGE:0,c,t,WS_CHILD|WS_VISIBLE|s,x,y,w,h,ui.w,(HMENU)(INT_PTR)id,GetModuleHandle(NULL),0); SendMessage(z,WM_SETFONT,(WPARAM)ui.normal,TRUE); if(page>=0&&ui.pc_count<32){ui.pc[ui.pc_count].h=z;ui.pc[ui.pc_count].page=page;++ui.pc_count;} return z; }
static HWND field(int id){return GetDlgItem(ui.w,id);}
static void center(HWND w,int ww,int hh){RECT r;SystemParametersInfo(SPI_GETWORKAREA,0,&r,0);SetWindowPos(w,0,r.left+(r.right-r.left-ww)/2,r.top+(r.bottom-r.top-hh)/2,ww,hh,SWP_NOZORDER|SWP_NOACTIVATE);}
static HMENU menu(void){HMENU bar=CreateMenu(),file=CreatePopupMenu(),settings=CreatePopupMenu(),help=CreatePopupMenu(),wallet=CreatePopupMenu(),sr=CreatePopupMenu(),tools=CreatePopupMenu();
 AppendMenuA(file,MF_STRING,M_EXIT,"Exit");AppendMenuA(bar,MF_POPUP,(UINT_PTR)file,"File");
 AppendMenuA(wallet,MF_STRING,M_WALLET_ADDRESS,"Address");AppendMenuA(wallet,MF_STRING,M_WALLET_IDENTITY,"Identity");AppendMenuA(wallet,MF_STRING,M_WALLET_CONTRACT,"Contract");AppendMenuA(bar,MF_POPUP,(UINT_PTR)wallet,"Wallet");
 AppendMenuA(sr,MF_STRING,M_SEND,"Send");AppendMenuA(sr,MF_STRING,M_RECEIVE,"Receive");AppendMenuA(bar,MF_POPUP,(UINT_PTR)sr,"Send/Receive");
 AppendMenuA(tools,MF_STRING,M_CONTRACTS,"Contracts");AppendMenuA(bar,MF_POPUP,(UINT_PTR)tools,"Tools");AppendMenuA(bar,MF_STRING,M_ACTIVITY,"Activity");
 AppendMenuA(settings,MF_STRING,M_MINING,"Mining");AppendMenuA(bar,MF_POPUP,(UINT_PTR)settings,"Settings");AppendMenuA(help,MF_STRING,M_ABOUT,"About STNC Core");AppendMenuA(bar,MF_POPUP,(UINT_PTR)help,"Help");return bar;}
static void show_page(int p){size_t i;if(p<0||p>=P_COUNT)return;ui.page=p;for(i=0;i<ui.pc_count;++i)ShowWindow(ui.pc[i].h,ui.pc[i].page==p?SW_SHOW:SW_HIDE);PostMessage(ui.w,UPDATED,0,0);}
static void queue(stnc_client_operation op){stnc_client_request *r=(stnc_client_request*)calloc(1,sizeof(*r));if(!r)return;r->operation=op;EnterCriticalSection(&ui.lock);if(!ui.ready||ui.busy||ui.stopping){LeaveCriticalSection(&ui.lock);free(r);return;}ui.pending=r;ui.busy=1;LeaveCriticalSection(&ui.lock);SetEvent(ui.wake);PostMessage(ui.w,UPDATED,0,0);}
static void copy_wallet(void){stnc_client_snapshot s;EnterCriticalSection(&ui.lock);s=ui.snap;LeaveCriticalSection(&ui.lock);if(!s.wallet.key_valid||!OpenClipboard(ui.w))return;{HGLOBAL m=GlobalAlloc(GMEM_MOVEABLE,strlen(s.wallet.address)+1);if(m){char *p=(char*)GlobalLock(m);memcpy(p,s.wallet.address,strlen(s.wallet.address)+1);GlobalUnlock(m);EmptyClipboard();SetClipboardData(CF_TEXT,m);}CloseClipboard();}}
static void send_now(void){char a[71],n[32],q[256];uint64_t u;stnc_client_request *r;GetWindowTextA(field(DESTINATION),a,sizeof(a));GetWindowTextA(field(AMOUNT),n,sizeof(n));if(!stnc_client_wallet_address_valid(a)||stnc_client_parse_units(n,&u)!=0){MessageBoxA(ui.w,"Enter a canonical stnw0_ address and a positive whole-unit amount.","Send STNC",MB_OK|MB_ICONWARNING);return;}snprintf(q,sizeof(q),"Send %" PRIu64 " STNC to\n%s?",u,a);if(MessageBoxA(ui.w,q,"Confirm send",MB_YESNO|MB_DEFBUTTON2|MB_ICONQUESTION)!=IDYES)return;r=(stnc_client_request*)calloc(1,sizeof(*r));if(!r)return;r->operation=STNC_CLIENT_SEND;r->confirmed=1;snprintf(r->address,sizeof(r->address),"%s",a);snprintf(r->units,sizeof(r->units),"%s",n);EnterCriticalSection(&ui.lock);if(ui.busy){LeaveCriticalSection(&ui.lock);free(r);return;}ui.pending=r;ui.busy=1;LeaveCriticalSection(&ui.lock);SetEvent(ui.wake);}
static void create_contract(void){stnc_client_request *r;OPENFILENAMEA d;char path[1024]="";int len,utf8;wchar_t *wide;stnc_client_snapshot s;
 EnterCriticalSection(&ui.lock);s=ui.snap;LeaveCriticalSection(&ui.lock);if(!s.identity.valid){MessageBoxA(ui.w,"Create an STN identity first. A Contract is an agreement object, not a wallet address.","New Contract",MB_OK|MB_ICONINFORMATION);return;}
 r=(stnc_client_request*)calloc(1,sizeof(*r));if(!r)return;r->operation=STNC_CLIENT_SAVE_DRAFT;r->draft.type=(uint16_t)(SendMessage(field(CONTRACT_TYPE),CB_GETCURSEL,0,0)+1);r->draft.created_at=(uint64_t)time(NULL);r->draft.participant_count=1;r->draft.participants[0].role=1;{size_t i;for(i=0;i<32;++i)snprintf(r->draft.participants[0].public_key+2*i,3,"%02x",(unsigned)s.identity.public_key[i]);}
 len=GetWindowTextLengthW(field(CONTRACT_TERMS));wide=(wchar_t*)calloc((size_t)len+1,sizeof(wchar_t));if(!wide){free(r);return;}GetWindowTextW(field(CONTRACT_TERMS),wide,len+1);utf8=WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,wide,len,(char*)r->terms,sizeof(r->terms),0,0);free(wide);if(len&&utf8<=0){MessageBoxA(ui.w,"Contract terms are too large or invalid UTF-8.","New Contract",MB_OK|MB_ICONWARNING);free(r);return;}r->draft.terms_length=(size_t)utf8;
 memset(&d,0,sizeof(d));d.lStructSize=sizeof(d);d.hwndOwner=ui.w;d.lpstrFilter="STN Contract draft (*.stct)\0*.stct\0All files\0*.*\0";d.lpstrFile=path;d.nMaxFile=sizeof(path);d.lpstrDefExt="stct";d.Flags=OFN_PATHMUSTEXIST|OFN_NOCHANGEDIR;if(!GetSaveFileNameA(&d)){free(r);return;}snprintf(r->path,sizeof(r->path),"%s",path);EnterCriticalSection(&ui.lock);if(ui.busy){LeaveCriticalSection(&ui.lock);free(r);return;}ui.pending=r;ui.busy=1;LeaveCriticalSection(&ui.lock);SetEvent(ui.wake);}
static DWORD WINAPI runtime(LPVOID x){stnc_client_snapshot s;uint64_t next=0;int ok;(void)x;ok=stnc_core_init()==0;EnterCriticalSection(&ui.lock);ui.ready=ok;ui.failed=!ok;LeaveCriticalSection(&ui.lock);PostMessage(ui.w,UPDATED,0,0);while(ok&&!InterlockedCompareExchange(&ui.stopping,0,0)){stnc_client_request *r=0;char out[4096];EnterCriticalSection(&ui.lock);r=ui.pending;ui.pending=0;LeaveCriticalSection(&ui.lock);if(r){stnc_client_execute(r,out,sizeof(out));free(r);EnterCriticalSection(&ui.lock);ui.busy=0;snprintf(ui.message,sizeof(ui.message),"%s",out);LeaveCriticalSection(&ui.lock);next=0;}if(stnc_core_tick()!=0)break;if(GetTickCount64()>=next){if(stnc_client_read(&s)==0){EnterCriticalSection(&ui.lock);ui.snap=s;LeaveCriticalSection(&ui.lock);}next=GetTickCount64()+1000;PostMessage(ui.w,UPDATED,0,0);}WaitForSingleObject(ui.wake,100);}if(ok){stnc_core_request_stop();stnc_core_shutdown();}PostMessage(ui.w,STOPPED,0,0);return 0;}
static void render(void){stnc_client_snapshot s;char b[64]="Unavailable",h[64]="--",t[4096],sync[160],msg[4096];int ready,busy;size_t i;EnterCriticalSection(&ui.lock);s=ui.snap;ready=ui.ready;busy=ui.busy;snprintf(msg,sizeof(msg),"%s",ui.message);LeaveCriticalSection(&ui.lock);if(s.wallet.balance_available)snprintf(b,sizeof(b),"%" PRIu64 " STNC",s.wallet.accepted_balance);if(s.chain.available)snprintf(h,sizeof(h),"%" PRIu64,s.chain.height);
 if(!ready){SetWindowTextA(ui.title,"STNC Core");SetWindowTextA(ui.content,ui.failed?"Core initialization failed.":"Connecting to STN Chain...");}
 else if(ui.page==P_OVERVIEW){SetWindowTextA(ui.title,"Overview");snprintf(t,sizeof(t),"STN CHAIN\r\nDistributed trust for verifiable intelligence and permanent records.\r\n\r\nBalance        %s\r\nWallet         %s\r\nIdentity       %s\r\nContracts      Verifiable agreements\r\nNetwork        %s\r\nMining         %s\r\nChain height   %s",b,s.wallet.key_valid?"Ready":"Not configured",s.identity.valid?"Ready":"Not configured",s.network.chain_connected?"Connected":"Disconnected",s.config.mining_enabled?"On":"Off",h);SetWindowTextA(ui.content,t);}
 else if(ui.page==P_SEND){SetWindowTextA(ui.title,"Send");snprintf(t,sizeof(t),"Available: %s\r\n\r\nPay to\r\n\r\n\r\nAmount",b);SetWindowTextA(ui.content,t);}
 else if(ui.page==P_RECEIVE){SetWindowTextA(ui.title,"Receive");snprintf(t,sizeof(t),"Receive STNC\r\n\r\n%s\r\n\r\nAccepted balance: %s",s.wallet.key_valid?s.wallet.address:"No wallet configured.",b);SetWindowTextA(ui.content,t);}
 else if(ui.page==P_WALLET_ADDRESS){SetWindowTextA(ui.title,"Wallet Address");snprintf(t,sizeof(t),"Address\r\n%s\r\n\r\nAccepted balance\r\n%s",s.wallet.key_valid?s.wallet.address:"No wallet exists.",b);SetWindowTextA(ui.content,t);}
 else if(ui.page==P_WALLET_IDENTITY){SetWindowTextA(ui.title,"Identity");snprintf(t,sizeof(t),"STN identity\r\n%s\r\n\r\nIdentity is separate from the economic wallet.",s.identity.valid?s.identity.address:"No identity exists.");SetWindowTextA(ui.content,t);}
 else if(ui.page==P_WALLET_CONTRACT||ui.page==P_CONTRACTS){SetWindowTextA(ui.title,ui.page==P_WALLET_CONTRACT?"Contract":"Contracts");snprintf(t,sizeof(t),"New STN Contract\r\n\r\nA Contract address (stnc0_) is deterministically created from the canonical Contract.\r\nIdentity: %s\r\n\r\nType\r\n\r\nTerms",s.identity.valid?s.identity.address:"Create an identity first.");SetWindowTextA(ui.content,t);SetWindowTextA(field(CONTRACT_RESULT),msg);}
 else if(ui.page==P_ACTIVITY){size_t used=0;SetWindowTextA(ui.title,"Activity");t[0]=0;for(i=0;i<s.activity_count&&i<5;++i){int n=snprintf(t+used,sizeof(t)-used,"%s%s",s.activity[i],i+1<s.activity_count?"\r\n\r\n":"");if(n<0||(size_t)n>=sizeof(t)-used)break;used+=(size_t)n;}if(!s.activity_count)snprintf(t,sizeof(t),"No recent activity.");SetWindowTextA(ui.content,t);}
 else {SetWindowTextA(ui.title,"Mining Settings");snprintf(t,sizeof(t),"Mining        %s\r\nRuntime       %s\r\nBackend       %s\r\nCPU limit     %u%%\r\nStratum       %s:%u\r\nHashrate      %" PRIu64 " H/s",s.config.mining_enabled?"On":"Off",s.mining.running?"Running":"Idle",s.mining.running?stnc_mining_backend_name(s.mining.active_backend):s.config.mining_backend,s.config.mining_cpu_limit_percent,s.config.stratum_host,(unsigned)s.config.stratum_port,s.mining.hashrate_hps);SetWindowTextA(ui.content,t);}
 ShowWindow(field(CREATE_WALLET),ui.page==P_WALLET_ADDRESS&&!s.wallet.present?SW_SHOW:SW_HIDE);ShowWindow(field(CREATE_IDENTITY),ui.page==P_WALLET_IDENTITY&&!s.identity.present?SW_SHOW:SW_HIDE);ShowWindow(field(COPY_ADDRESS),ui.page==P_RECEIVE&&s.wallet.key_valid?SW_SHOW:SW_HIDE);
 EnableWindow(field(MINING_ON),ready&&!busy&&s.wallet.key_valid&&!s.config.mining_enabled);EnableWindow(field(MINING_OFF),ready&&!busy&&s.config.mining_enabled);EnableWindow(field(SEND),ready&&!busy&&s.wallet.key_valid);EnableWindow(field(CREATE_CONTRACT),ready&&!busy&&s.identity.valid);
 if(!ready)snprintf(sync,sizeof(sync),"Starting Core...");else if(!s.network.chain_connected)snprintf(sync,sizeof(sync),"Disconnected");else if(s.network.peer_current)snprintf(sync,sizeof(sync),"Synchronized  |  Height %s",h);else snprintf(sync,sizeof(sync),"Synchronizing  |  Height %s",h);SetWindowTextA(ui.sync,sync);ShowWindow(ui.progress,ready&&s.network.chain_connected&&!s.network.peer_current?SW_SHOW:SW_HIDE);SendMessage(ui.progress,PBM_SETMARQUEE,TRUE,0);}
static LRESULT CALLBACK proc(HWND w,UINT m,WPARAM wp,LPARAM lp){(void)lp;switch(m){case WM_COMMAND:switch(LOWORD(wp)){case B_OVERVIEW:show_page(P_OVERVIEW);break;case B_SEND:case M_SEND:show_page(P_SEND);break;case B_RECEIVE:case M_RECEIVE:show_page(P_RECEIVE);break;case B_WALLET:case M_WALLET_ADDRESS:show_page(P_WALLET_ADDRESS);break;case M_WALLET_IDENTITY:show_page(P_WALLET_IDENTITY);break;case M_WALLET_CONTRACT:show_page(P_WALLET_CONTRACT);break;case B_CONTRACTS:case M_CONTRACTS:show_page(P_CONTRACTS);break;case B_ACTIVITY:case M_ACTIVITY:show_page(P_ACTIVITY);break;case M_MINING:show_page(P_MINING);break;case M_EXIT:PostMessage(w,WM_CLOSE,0,0);break;case M_ABOUT:MessageBoxA(w,"STNC Core\nSTN Chain desktop client","About",MB_OK|MB_ICONINFORMATION);break;case CREATE_WALLET:queue(STNC_CLIENT_CREATE_WALLET);break;case CREATE_IDENTITY:queue(STNC_CLIENT_CREATE_IDENTITY);break;case SEND:send_now();break;case COPY_ADDRESS:copy_wallet();break;case MINING_ON:queue(STNC_CLIENT_MINING_ON);break;case MINING_OFF:queue(STNC_CLIENT_MINING_OFF);break;case CPU_SAVE:{stnc_client_request *r=(stnc_client_request*)calloc(1,sizeof(*r));if(r){r->operation=STNC_CLIENT_CPU_LIMIT;r->cpu_limit=(unsigned)SendMessage(field(CPU),CB_GETCURSEL,0,0)+1;EnterCriticalSection(&ui.lock);if(!ui.busy){ui.pending=r;ui.busy=1;r=0;}LeaveCriticalSection(&ui.lock);if(r)free(r);else SetEvent(ui.wake);}break;}case CREATE_CONTRACT:create_contract();break;}return 0;case UPDATED:render();return 0;case STOPPED:if(ui.stopping)DestroyWindow(w);return 0;case WM_CLOSE:InterlockedExchange(&ui.stopping,1);SetEvent(ui.wake);SetWindowTextA(w,"STNC Core - stopping...");return 0;case WM_DESTROY:PostQuitMessage(0);return 0;default:return DefWindowProcA(w,m,wp,lp);}}
int stnc_gui_run(void){WNDCLASSA c;MSG msg;INITCOMMONCONTROLSEX ic;int i;const char *names[]={"Overview","Send","Receive","Wallet","Contracts","Activity"};int ids[]={B_OVERVIEW,B_SEND,B_RECEIVE,B_WALLET,B_CONTRACTS,B_ACTIVITY};const char *types[]={"Generic","Work Offer","Contributor Agreement","Policy","Organizational Decision","Service Agreement"};FreeConsole();memset(&ui,0,sizeof(ui));InitializeCriticalSection(&ui.lock);ui.wake=CreateEvent(0,FALSE,FALSE,0);ui.normal=CreateFontA(-15,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");ui.bold=CreateFontA(-16,0,0,0,FW_SEMIBOLD,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");ui.titlefont=CreateFontA(-22,0,0,0,FW_SEMIBOLD,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");ui.navfont=CreateFontA(-14,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");ic.dwSize=sizeof(ic);ic.dwICC=ICC_PROGRESS_CLASS;InitCommonControlsEx(&ic);memset(&c,0,sizeof(c));c.lpfnWndProc=proc;c.hInstance=GetModuleHandle(0);c.lpszClassName="STNCCoreWindow";c.hCursor=LoadCursor(0,IDC_ARROW);c.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassA(&c);ui.w=CreateWindowExA(0,c.lpszClassName,"STNC Core",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX,CW_USEDEFAULT,CW_USEDEFAULT,680,460,0,menu(),c.hInstance,0);if(!ui.w)return 1;center(ui.w,680,460);
 for(i=0;i<6;++i){ui.nav[i]=ctl("BUTTON",names[i],BS_FLAT|BS_PUSHBUTTON,ids[i],-1,12+i*106,8,100,30);SendMessage(ui.nav[i],WM_SETFONT,(WPARAM)ui.navfont,TRUE);}ui.title=ctl("STATIC","Overview",0,0,-1,24,54,620,28);SendMessage(ui.title,WM_SETFONT,(WPARAM)ui.titlefont,TRUE);ui.content=ctl("STATIC","Starting Core...",SS_LEFT,0,-1,24,92,620,260);ui.sync=ctl("STATIC","Starting Core...",0,0,-1,12,385,260,20);ui.progress=ctl(PROGRESS_CLASSA,"",PBS_MARQUEE,0,-1,280,388,370,14);
 ctl("EDIT","",ES_AUTOHSCROLL|WS_BORDER,DESTINATION,P_SEND,120,180,500,24);ctl("EDIT","",ES_AUTOHSCROLL|WS_BORDER,AMOUNT,P_SEND,120,236,160,24);ctl("BUTTON","Send",BS_PUSHBUTTON,SEND,P_SEND,520,282,100,28);ctl("BUTTON","Copy address",BS_PUSHBUTTON,COPY_ADDRESS,P_RECEIVE,500,205,120,28);
 ctl("BUTTON","Create wallet",BS_PUSHBUTTON,CREATE_WALLET,P_WALLET_ADDRESS,490,205,130,28);ctl("BUTTON","Create identity",BS_PUSHBUTTON,CREATE_IDENTITY,P_WALLET_IDENTITY,490,205,130,28);
 {HWND cb=ctl("COMBOBOX","",CBS_DROPDOWNLIST|WS_VSCROLL,CONTRACT_TYPE,P_WALLET_CONTRACT,120,205,250,160);for(i=0;i<6;++i)SendMessageA(cb,CB_ADDSTRING,0,(LPARAM)types[i]);SendMessage(cb,CB_SETCURSEL,0,0);}ctl("EDIT","",ES_MULTILINE|ES_WANTRETURN|WS_VSCROLL|WS_BORDER,CONTRACT_TERMS,P_WALLET_CONTRACT,120,255,500,70);ctl("BUTTON","Create Contract",BS_PUSHBUTTON,CREATE_CONTRACT,P_WALLET_CONTRACT,490,335,130,28);ctl("STATIC","",SS_LEFT,CONTRACT_RESULT,P_WALLET_CONTRACT,24,335,450,42);
 {HWND cb=ctl("COMBOBOX","",CBS_DROPDOWNLIST|WS_VSCROLL,CONTRACT_TYPE+100,P_CONTRACTS,120,205,250,160);for(i=0;i<6;++i)SendMessageA(cb,CB_ADDSTRING,0,(LPARAM)types[i]);SendMessage(cb,CB_SETCURSEL,0,0);}
 ctl("BUTTON","Turn mining on",BS_PUSHBUTTON,MINING_ON,P_MINING,360,250,120,28);ctl("BUTTON","Turn mining off",BS_PUSHBUTTON,MINING_OFF,P_MINING,492,250,128,28);{HWND cb=ctl("COMBOBOX","",CBS_DROPDOWNLIST,CPU,P_MINING,360,294,80,100);SendMessageA(cb,CB_ADDSTRING,0,(LPARAM)"1%");SendMessageA(cb,CB_ADDSTRING,0,(LPARAM)"2%");SendMessage(cb,CB_SETCURSEL,1,0);}ctl("BUTTON","Save CPU limit",BS_PUSHBUTTON,CPU_SAVE,P_MINING,452,292,128,28);
 for(i=0;i<(int)ui.pc_count;++i)ShowWindow(ui.pc[i].h,SW_HIDE);ShowWindow(ui.w,SW_SHOW);UpdateWindow(ui.w);show_page(P_OVERVIEW);ui.thread=CreateThread(0,0,runtime,0,0,0);while(GetMessage(&msg,0,0,0)>0){if(!IsDialogMessage(ui.w,&msg)){TranslateMessage(&msg);DispatchMessage(&msg);}}WaitForSingleObject(ui.thread,INFINITE);CloseHandle(ui.thread);CloseHandle(ui.wake);DeleteCriticalSection(&ui.lock);DeleteObject(ui.normal);DeleteObject(ui.bold);DeleteObject(ui.titlefont);DeleteObject(ui.navfont);return 0;}
