#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <commctrl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include "stnc_gui.h"
#include "stnc_client.h"

#define UI_UPDATED (WM_APP+1)
#define UI_STOPPED (WM_APP+2)
enum { ID_OVERVIEW=500,ID_SEND,ID_RECEIVE,ID_WALLET,ID_CONTRACTS,ID_ACTIVITY,ID_SETTINGS,
 ID_CREATE_WALLET=520,ID_CREATE_IDENTITY,ID_SEND_NOW,ID_DESTINATION,ID_AMOUNT,ID_COPY,
 ID_MINING_ON,ID_MINING_OFF };
enum { PAGE_OVERVIEW,PAGE_SEND,PAGE_RECEIVE,PAGE_WALLET,PAGE_CONTRACTS,PAGE_ACTIVITY,PAGE_MINING };
static struct { HWND window,title,body,sync,progress; HFONT normal,title_font,nav_font; HANDLE wake,thread;
 CRITICAL_SECTION lock; volatile LONG stopping; int ready,busy,page; stnc_client_request *pending;
 stnc_client_snapshot snapshot; } ui;

static HWND control(const char *klass,const char *text,DWORD style,int id,int x,int y,int w,int h){HWND z=CreateWindowExA(strcmp(klass,"EDIT")==0?WS_EX_CLIENTEDGE:0,klass,text,WS_CHILD|WS_VISIBLE|style,x,y,w,h,ui.window,(HMENU)(INT_PTR)id,GetModuleHandle(NULL),NULL);SendMessage(z,WM_SETFONT,(WPARAM)ui.normal,TRUE);return z;}
static void center(HWND w,int width,int height){RECT r;SystemParametersInfo(SPI_GETWORKAREA,0,&r,0);SetWindowPos(w,NULL,r.left+(r.right-r.left-width)/2,r.top+(r.bottom-r.top-height)/2,width,height,SWP_NOZORDER);}
static void set_page(int page){ui.page=page;PostMessage(ui.window,UI_UPDATED,0,0);}
static void hide_actions(void){int ids[]={ID_CREATE_WALLET,ID_CREATE_IDENTITY,ID_SEND_NOW,ID_DESTINATION,ID_AMOUNT,ID_COPY,ID_MINING_ON,ID_MINING_OFF};size_t i;for(i=0;i<sizeof(ids)/sizeof(ids[0]);++i)ShowWindow(GetDlgItem(ui.window,ids[i]),SW_HIDE);}
static void queue(stnc_client_operation op){stnc_client_request *r=(stnc_client_request*)calloc(1,sizeof(*r));if(!r)return;r->operation=op;EnterCriticalSection(&ui.lock);if(!ui.ready||ui.busy){LeaveCriticalSection(&ui.lock);free(r);return;}ui.pending=r;ui.busy=1;LeaveCriticalSection(&ui.lock);SetEvent(ui.wake);}
static void copy_wallet(void){stnc_client_snapshot s;EnterCriticalSection(&ui.lock);s=ui.snapshot;LeaveCriticalSection(&ui.lock);if(!s.wallet.key_valid||!OpenClipboard(ui.window))return;{HGLOBAL m=GlobalAlloc(GMEM_MOVEABLE,strlen(s.wallet.address)+1);if(m){char *p=(char*)GlobalLock(m);memcpy(p,s.wallet.address,strlen(s.wallet.address)+1);GlobalUnlock(m);EmptyClipboard();SetClipboardData(CF_TEXT,m);}CloseClipboard();}}
static void send_payment(void){char address[71],amount[32],prompt[256];uint64_t units;stnc_client_request *r;GetWindowTextA(GetDlgItem(ui.window,ID_DESTINATION),address,sizeof(address));GetWindowTextA(GetDlgItem(ui.window,ID_AMOUNT),amount,sizeof(amount));if(!stnc_client_wallet_address_valid(address)||stnc_client_parse_units(amount,&units)!=0){MessageBoxA(ui.window,"Enter a valid stnw0_ address and positive whole-unit amount.","Send STNC",MB_OK|MB_ICONWARNING);return;}snprintf(prompt,sizeof(prompt),"Send %" PRIu64 " STNC to\n%s?",units,address);if(MessageBoxA(ui.window,prompt,"Confirm send",MB_YESNO|MB_DEFBUTTON2|MB_ICONQUESTION)!=IDYES)return;r=(stnc_client_request*)calloc(1,sizeof(*r));if(!r)return;r->operation=STNC_CLIENT_SEND;r->confirmed=1;snprintf(r->address,sizeof(r->address),"%s",address);snprintf(r->units,sizeof(r->units),"%s",amount);EnterCriticalSection(&ui.lock);if(ui.busy){LeaveCriticalSection(&ui.lock);free(r);return;}ui.pending=r;ui.busy=1;LeaveCriticalSection(&ui.lock);SetEvent(ui.wake);}
static DWORD WINAPI runtime(LPVOID unused){stnc_client_snapshot s;uint64_t next=0;int ok;(void)unused;ok=stnc_core_init()==0;EnterCriticalSection(&ui.lock);ui.ready=ok;LeaveCriticalSection(&ui.lock);PostMessage(ui.window,UI_UPDATED,0,0);while(ok&&!InterlockedCompareExchange(&ui.stopping,0,0)){stnc_client_request *r=NULL;char message[512];EnterCriticalSection(&ui.lock);r=ui.pending;ui.pending=NULL;LeaveCriticalSection(&ui.lock);if(r){stnc_client_execute(r,message,sizeof(message));free(r);EnterCriticalSection(&ui.lock);ui.busy=0;LeaveCriticalSection(&ui.lock);next=0;}if(stnc_core_tick()!=0)break;if(GetTickCount64()>=next){if(stnc_client_read(&s)==0){EnterCriticalSection(&ui.lock);ui.snapshot=s;LeaveCriticalSection(&ui.lock);}next=GetTickCount64()+2000;PostMessage(ui.window,UI_UPDATED,0,0);}WaitForSingleObject(ui.wake,100);}if(ok){stnc_core_request_stop();stnc_core_shutdown();}PostMessage(ui.window,UI_STOPPED,0,0);return 0;}
static void render(void){stnc_client_snapshot s;char balance[64]="Unavailable",height[32]="--",text[4096],sync[128];size_t i,used=0;int ready,busy;EnterCriticalSection(&ui.lock);s=ui.snapshot;ready=ui.ready;busy=ui.busy;LeaveCriticalSection(&ui.lock);hide_actions();if(s.wallet.balance_available)snprintf(balance,sizeof(balance),"%" PRIu64 " STNC",s.wallet.accepted_balance);if(s.chain.available)snprintf(height,sizeof(height),"%" PRIu64,s.chain.height);
 if(!ready){SetWindowTextA(ui.title,"STNC Core");SetWindowTextA(ui.body,"Connecting to STN Chain...");}
 else if(ui.page==PAGE_OVERVIEW){SetWindowTextA(ui.title,"Overview");snprintf(text,sizeof(text),"STN CHAIN\r\nDistributed trust for verifiable intelligence\r\n\r\nBalance        %s\r\nWallet         %s\r\nIdentity       %s\r\nContracts      Verifiable agreements\r\nRecords        Permanent Chain records\r\n\r\nNetwork        %s\r\nMining         %s   %" PRIu64 " H/s\r\nChain height   %s",balance,s.wallet.key_valid?"Ready":"Not configured",s.identity.valid?"Ready":"Not configured",s.network.chain_connected?"Connected":"Disconnected",s.mining.running?"Running":"Idle",s.mining.hashrate_hps,height);SetWindowTextA(ui.body,text);}
 else if(ui.page==PAGE_SEND){SetWindowTextA(ui.title,"Send STNC");snprintf(text,sizeof(text),"Available: %s\r\n\r\nPay to\r\n\r\n\r\nAmount",balance);SetWindowTextA(ui.body,text);ShowWindow(GetDlgItem(ui.window,ID_DESTINATION),SW_SHOW);ShowWindow(GetDlgItem(ui.window,ID_AMOUNT),SW_SHOW);ShowWindow(GetDlgItem(ui.window,ID_SEND_NOW),SW_SHOW);}
 else if(ui.page==PAGE_RECEIVE){SetWindowTextA(ui.title,"Receive STNC");snprintf(text,sizeof(text),"Receiving address\r\n\r\n%s\r\n\r\nAccepted balance: %s",s.wallet.key_valid?s.wallet.address:"No wallet configured.",balance);SetWindowTextA(ui.body,text);if(s.wallet.key_valid)ShowWindow(GetDlgItem(ui.window,ID_COPY),SW_SHOW);}
 else if(ui.page==PAGE_WALLET){SetWindowTextA(ui.title,"Wallet");snprintf(text,sizeof(text),"ADDRESS\r\n%s\r\n\r\nBALANCE\r\n%s\r\n\r\nIDENTITY\r\n%s\r\n\r\nCONTRACT ADDRESS\r\nNot configured",s.wallet.key_valid?s.wallet.address:"No wallet configured.",balance,s.identity.valid?s.identity.address:"No identity configured.");SetWindowTextA(ui.body,text);if(!s.wallet.present)ShowWindow(GetDlgItem(ui.window,ID_CREATE_WALLET),SW_SHOW);if(!s.identity.present)ShowWindow(GetDlgItem(ui.window,ID_CREATE_IDENTITY),SW_SHOW);}
 else if(ui.page==PAGE_CONTRACTS){SetWindowTextA(ui.title,"Contracts");SetWindowTextA(ui.body,"STN Chain Contracts\r\n\r\nCreate, inspect, and manage verifiable agreements.\r\nContract actions remain bounded by accepted identity and authority evidence.");}
 else if(ui.page==PAGE_ACTIVITY){SetWindowTextA(ui.title,"Activity");text[0]=0;for(i=0;i<s.activity_count&&i<5;++i){int n=snprintf(text+used,sizeof(text)-used,"%s%s",s.activity[i],i+1<s.activity_count?"\r\n\r\n":"");if(n<0||(size_t)n>=sizeof(text)-used)break;used+=(size_t)n;}if(!s.activity_count)snprintf(text,sizeof(text),"No recent activity.");SetWindowTextA(ui.body,text);}
 else {SetWindowTextA(ui.title,"Mining Settings");snprintf(text,sizeof(text),"Mining is %s\r\n\r\nBackend       %s\r\nCPU limit     %u%%\r\nStratum       %s:%u\r\nHashrate      %" PRIu64 " H/s",s.mining.running?"ON":"OFF",s.mining.running?stnc_mining_backend_name(s.mining.active_backend):s.config.mining_backend,s.config.mining_cpu_limit_percent,s.config.stratum_host,(unsigned)s.config.stratum_port,s.mining.hashrate_hps);SetWindowTextA(ui.body,text);ShowWindow(GetDlgItem(ui.window,ID_MINING_ON),SW_SHOW);ShowWindow(GetDlgItem(ui.window,ID_MINING_OFF),SW_SHOW);EnableWindow(GetDlgItem(ui.window,ID_MINING_ON),ready&&!busy&&s.wallet.key_valid);EnableWindow(GetDlgItem(ui.window,ID_MINING_OFF),ready&&!busy);}
 if(!ready)snprintf(sync,sizeof(sync),"Starting Core...");else if(!s.network.chain_connected)snprintf(sync,sizeof(sync),"Disconnected");else if(s.network.peer_current)snprintf(sync,sizeof(sync),"Synchronized   |   Height %s",height);else snprintf(sync,sizeof(sync),"Synchronizing   |   Height %s",height);SetWindowTextA(ui.sync,sync);ShowWindow(ui.progress,ready&&s.network.chain_connected&&!s.network.peer_current?SW_SHOW:SW_HIDE);SendMessage(ui.progress,PBM_SETMARQUEE,TRUE,0);}
static LRESULT CALLBACK window_proc(HWND w,UINT m,WPARAM wp,LPARAM lp){(void)lp;switch(m){case WM_COMMAND:switch(LOWORD(wp)){case ID_OVERVIEW:set_page(PAGE_OVERVIEW);break;case ID_SEND:set_page(PAGE_SEND);break;case ID_RECEIVE:set_page(PAGE_RECEIVE);break;case ID_WALLET:set_page(PAGE_WALLET);break;case ID_CONTRACTS:set_page(PAGE_CONTRACTS);break;case ID_ACTIVITY:set_page(PAGE_ACTIVITY);break;case ID_SETTINGS:set_page(PAGE_MINING);break;case ID_CREATE_WALLET:queue(STNC_CLIENT_CREATE_WALLET);break;case ID_CREATE_IDENTITY:queue(STNC_CLIENT_CREATE_IDENTITY);break;case ID_SEND_NOW:send_payment();break;case ID_COPY:copy_wallet();break;case ID_MINING_ON:queue(STNC_CLIENT_MINING_ON);break;case ID_MINING_OFF:queue(STNC_CLIENT_MINING_OFF);break;}return 0;case UI_UPDATED:render();return 0;case UI_STOPPED:if(ui.stopping)DestroyWindow(w);return 0;case WM_CLOSE:InterlockedExchange(&ui.stopping,1);SetEvent(ui.wake);return 0;case WM_DESTROY:PostQuitMessage(0);return 0;default:return DefWindowProcA(w,m,wp,lp);}}
int stnc_gui_wallet_run(void){WNDCLASSA c;MSG msg;INITCOMMONCONTROLSEX ic;int i;const char *names[]={"Overview","Send","Receive","Wallet","Contracts","Activity","Settings"};int ids[]={ID_OVERVIEW,ID_SEND,ID_RECEIVE,ID_WALLET,ID_CONTRACTS,ID_ACTIVITY,ID_SETTINGS};FreeConsole();memset(&ui,0,sizeof(ui));InitializeCriticalSection(&ui.lock);ui.wake=CreateEvent(NULL,FALSE,FALSE,NULL);ui.normal=CreateFontA(-15,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");ui.title_font=CreateFontA(-23,0,0,0,FW_SEMIBOLD,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");ui.nav_font=CreateFontA(-14,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");ic.dwSize=sizeof(ic);ic.dwICC=ICC_PROGRESS_CLASS;InitCommonControlsEx(&ic);memset(&c,0,sizeof(c));c.lpfnWndProc=window_proc;c.hInstance=GetModuleHandle(NULL);c.lpszClassName="STNCCoreWindow";c.hCursor=LoadCursor(NULL,IDC_ARROW);c.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassA(&c);ui.window=CreateWindowExA(0,c.lpszClassName,"STNC Core",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX,CW_USEDEFAULT,CW_USEDEFAULT,760,500,NULL,NULL,c.hInstance,NULL);if(!ui.window)return 1;center(ui.window,760,500);for(i=0;i<7;++i){HWND b=control("BUTTON",names[i],BS_FLAT|BS_PUSHBUTTON,ids[i],10+i*105,10,98,31);SendMessage(b,WM_SETFONT,(WPARAM)ui.nav_font,TRUE);}ui.title=control("STATIC","Overview",0,0,26,58,690,30);SendMessage(ui.title,WM_SETFONT,(WPARAM)ui.title_font,TRUE);ui.body=control("STATIC","Starting Core...",SS_LEFT,0,26,98,690,285);ui.sync=control("STATIC","Starting Core...",0,0,14,438,260,20);ui.progress=control(PROGRESS_CLASSA,"",PBS_MARQUEE,0,280,440,455,15);control("EDIT","",ES_AUTOHSCROLL,ID_DESTINATION,135,190,550,25);control("EDIT","",ES_AUTOHSCROLL,ID_AMOUNT,135,245,160,25);control("BUTTON","Send",BS_PUSHBUTTON,ID_SEND_NOW,575,285,110,30);control("BUTTON","Copy address",BS_PUSHBUTTON,ID_COPY,565,190,120,30);control("BUTTON","Create wallet",BS_PUSHBUTTON,ID_CREATE_WALLET,545,275,140,30);control("BUTTON","Create identity",BS_PUSHBUTTON,ID_CREATE_IDENTITY,545,315,140,30);control("BUTTON","Turn mining on",BS_PUSHBUTTON,ID_MINING_ON,440,280,120,30);control("BUTTON","Turn mining off",BS_PUSHBUTTON,ID_MINING_OFF,570,280,120,30);hide_actions();ShowWindow(ui.window,SW_SHOW);UpdateWindow(ui.window);ui.thread=CreateThread(NULL,0,runtime,NULL,0,NULL);while(GetMessage(&msg,NULL,0,0)>0){TranslateMessage(&msg);DispatchMessage(&msg);}WaitForSingleObject(ui.thread,INFINITE);CloseHandle(ui.thread);CloseHandle(ui.wake);DeleteCriticalSection(&ui.lock);DeleteObject(ui.normal);DeleteObject(ui.title_font);DeleteObject(ui.nav_font);return 0;}
