#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <commctrl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include "stnc_gui.h"
#include "stnc_client.h"

#define UPDATED (WM_APP+1)
#define STOPPED (WM_APP+2)
enum { B_OVERVIEW=300,B_SEND,B_RECEIVE,B_WALLET,B_CONTRACTS,B_ACTIVITY,
       CREATE_WALLET=320,CREATE_IDENTITY,SEND_NOW,DESTINATION,AMOUNT,COPY_ADDRESS,
       MINING_ON,MINING_OFF };
enum { P_OVERVIEW,P_SEND,P_RECEIVE,P_WALLET,P_CONTRACTS,P_ACTIVITY,P_MINING };
static struct { HWND w,title,content,sync,progress; HWND buttons[6]; HFONT normal,bold,hero,nav;
 CRITICAL_SECTION lock; HANDLE wake,thread; volatile LONG stopping; int ready,busy,page;
 stnc_client_request *pending; stnc_client_snapshot snap; char message[512]; } ui;

static HWND ctl(const char *c,const char *t,DWORD s,int id,int x,int y,int w,int h){HWND z=CreateWindowExA(strcmp(c,"EDIT")==0?WS_EX_CLIENTEDGE:0,c,t,WS_CHILD|WS_VISIBLE|s,x,y,w,h,ui.w,(HMENU)(INT_PTR)id,GetModuleHandle(NULL),0);SendMessage(z,WM_SETFONT,(WPARAM)ui.normal,TRUE);return z;}
static void center(HWND w,int ww,int hh){RECT r;SystemParametersInfo(SPI_GETWORKAREA,0,&r,0);SetWindowPos(w,0,r.left+(r.right-r.left-ww)/2,r.top+(r.bottom-r.top-hh)/2,ww,hh,SWP_NOZORDER);}
static void page(int p){ui.page=p;InvalidateRect(ui.w,0,TRUE);PostMessage(ui.w,UPDATED,0,0);}
static void queue(stnc_client_operation op){stnc_client_request *r=(stnc_client_request*)calloc(1,sizeof(*r));if(!r)return;r->operation=op;EnterCriticalSection(&ui.lock);if(!ui.ready||ui.busy){LeaveCriticalSection(&ui.lock);free(r);return;}ui.pending=r;ui.busy=1;LeaveCriticalSection(&ui.lock);SetEvent(ui.wake);}
static void copy_address(void){stnc_client_snapshot s;EnterCriticalSection(&ui.lock);s=ui.snap;LeaveCriticalSection(&ui.lock);if(!s.wallet.key_valid||!OpenClipboard(ui.w))return;{HGLOBAL m=GlobalAlloc(GMEM_MOVEABLE,strlen(s.wallet.address)+1);if(m){char *p=(char*)GlobalLock(m);strcpy(p,s.wallet.address);GlobalUnlock(m);EmptyClipboard();SetClipboardData(CF_TEXT,m);}CloseClipboard();}}
static void send_now(void){char a[71],n[32],q[256];uint64_t u;stnc_client_request *r;GetWindowTextA(GetDlgItem(ui.w,DESTINATION),a,sizeof(a));GetWindowTextA(GetDlgItem(ui.w,AMOUNT),n,sizeof(n));if(!stnc_client_wallet_address_valid(a)||stnc_client_parse_units(n,&u)!=0){MessageBoxA(ui.w,"Enter a valid STNC wallet address and positive whole-unit amount.","Send STNC",MB_OK|MB_ICONWARNING);return;}snprintf(q,sizeof(q),"Send %" PRIu64 " STNC to\n%s?",u,a);if(MessageBoxA(ui.w,q,"Confirm send",MB_YESNO|MB_DEFBUTTON2|MB_ICONQUESTION)!=IDYES)return;r=(stnc_client_request*)calloc(1,sizeof(*r));if(!r)return;r->operation=STNC_CLIENT_SEND;r->confirmed=1;strcpy(r->address,a);strcpy(r->units,n);EnterCriticalSection(&ui.lock);if(ui.busy){LeaveCriticalSection(&ui.lock);free(r);return;}ui.pending=r;ui.busy=1;LeaveCriticalSection(&ui.lock);SetEvent(ui.wake);}
static DWORD WINAPI runtime(LPVOID x){stnc_client_snapshot s;uint64_t next=0;int ok;(void)x;ok=stnc_core_init()==0;EnterCriticalSection(&ui.lock);ui.ready=ok;LeaveCriticalSection(&ui.lock);PostMessage(ui.w,UPDATED,0,0);while(ok&&!InterlockedCompareExchange(&ui.stopping,0,0)){stnc_client_request *r=0;char out[512];EnterCriticalSection(&ui.lock);r=ui.pending;ui.pending=0;LeaveCriticalSection(&ui.lock);if(r){stnc_client_execute(r,out,sizeof(out));free(r);EnterCriticalSection(&ui.lock);ui.busy=0;snprintf(ui.message,sizeof(ui.message),"%s",out);LeaveCriticalSection(&ui.lock);next=0;}if(stnc_core_tick()!=0)break;if(GetTickCount64()>=next){if(stnc_client_read(&s)==0){EnterCriticalSection(&ui.lock);ui.snap=s;LeaveCriticalSection(&ui.lock);}next=GetTickCount64()+2000;PostMessage(ui.w,UPDATED,0,0);}WaitForSingleObject(ui.wake,100);}if(ok){stnc_core_request_stop();stnc_core_shutdown();}PostMessage(ui.w,STOPPED,0,0);return 0;}
static void hide_actions(void){int ids[]={CREATE_WALLET,CREATE_IDENTITY,SEND_NOW,DESTINATION,AMOUNT,COPY_ADDRESS,MINING_ON,MINING_OFF};size_t i;for(i=0;i<sizeof(ids)/sizeof(ids[0]);++i){HWND h=GetDlgItem(ui.w,ids[i]);if(h)ShowWindow(h,SW_HIDE);}}
static void render(void){stnc_client_snapshot s;char b[64]="Unavailable",h[64]="--",t[4096],sync[128];int ready;EnterCriticalSection(&ui.lock);s=ui.snap;ready=ui.ready;LeaveCriticalSection(&ui.lock);hide_actions();if(s.wallet.balance_available)snprintf(b,sizeof(b),"%" PRIu64 " STNC",s.wallet.accepted_balance);if(s.chain.available)snprintf(h,sizeof(h),"%" PRIu64,s.chain.height);
 if(!ready){SetWindowTextA(ui.title,"STNC Core");SetWindowTextA(ui.content,"Connecting to STN Chain...");}
 else if(ui.page==P_OVERVIEW){SetWindowTextA(ui.title,"Overview");snprintf(t,sizeof(t),"STN CHAIN\r\nDistributed trust for verifiable intelligence\r\n\r\nBalance                         %s\r\n\r\nWallet                          %s\r\nIdentity                        %s\r\nContracts                       Verifiable agreements\r\nRecords                         Permanent Chain records\r\nNetwork                         %s\r\nMining                          %s   %" PRIu64 " H/s\r\n\r\nAccepted Chain height           %s",b,s.wallet.key_valid?"Ready":"Not configured",s.identity.valid?"Ready":"Not configured",s.network.chain_connected?"Connected":"Disconnected",s.mining.running?"Running":"Idle",s.mining.hashrate_hps,h);SetWindowTextA(ui.content,t);}
 else if(ui.page==P_SEND){SetWindowTextA(ui.title,"Send STNC");snprintf(t,sizeof(t),"Available balance: %s\r\n\r\nPay to\r\n\r\n\r\nAmount",b);SetWindowTextA(ui.content,t);ShowWindow(GetDlgItem(ui.w,DESTINATION),SW_SHOW);ShowWindow(GetDlgItem(ui.w,AMOUNT),SW_SHOW);ShowWindow(GetDlgItem(ui.w,SEND_NOW),SW_SHOW);}
 else if(ui.page==P_RECEIVE){SetWindowTextA(ui.title,"Receive STNC");snprintf(t,sizeof(t),"Your receiving address\r\n\r\n%s\r\n\r\nGive this address to the sender.\r\nAccepted balance: %s",s.wallet.key_valid?s.wallet.address:"No wallet configured.",b);SetWindowTextA(ui.content,t);if(s.wallet.key_valid)ShowWindow(GetDlgItem(ui.w,COPY_ADDRESS),SW_SHOW);}
 else if(ui.page==P_WALLET){SetWindowTextA(ui.title,"Wallet");snprintf(t,sizeof(t),"ADDRESS\r\n%s\r\n\r\nBALANCE\r\n%s\r\n\r\nIDENTITY\r\n%s\r\n\r\nCONTRACT IDENTITY\r\nContracts use Core identity and accepted authority evidence.",s.wallet.key_valid?s.wallet.address:"No wallet configured.",b,s.identity.valid?s.identity.address:"No identity configured.");SetWindowTextA(ui.content,t);if(!s.wallet.present)ShowWindow(GetDlgItem(ui.w,CREATE_WALLET),SW_SHOW);if(!s.identity.present)ShowWindow(GetDlgItem(ui.w,CREATE_IDENTITY),SW_SHOW);}
 else if(ui.page==P_CONTRACTS){SetWindowTextA(ui.title,"Contracts");SetWindowTextA(ui.content,"STN Chain Contracts\r\n\r\nVerifiable agreements are identified independently from wallets and identities.\r\n\r\nContract lifecycle operations require accepted identity and authority evidence.");}
 else if(ui.page==P_ACTIVITY){size_t i,u=0;SetWindowTextA(ui.title,"Activity");t[0]=0;for(i=0;i<s.activity_count&&i<5;++i){int n=snprintf(t+u,sizeof(t)-u,"%s%s",s.activity[i],i+1<s.activity_count?"\r\n\r\n":"");if(n<0||(size_t)n>=sizeof(t)-u)break;u+=(size_t)n;}if(!s.activity_count)strcpy(t,"No recent activity.");SetWindowTextA(ui.content,t);}
 else {SetWindowTextA(ui.title,"Mining Settings");snprintf(t,sizeof(t),"Status          %s\r\nBackend         %s\r\nCPU limit       %u%%\r\nStratum         %s:%u\r\nHashrate        %" PRIu64 " H/s",s.mining.running?"Running":"Idle",s.mining.running?stnc_mining_backend_name(s.mining.active_backend):s.config.mining_backend,s.config.mining_cpu_limit_percent,s.config.stratum_host,(unsigned)s.config.stratum_port,s.mining.hashrate_hps);SetWindowTextA(ui.content,t);ShowWindow(GetDlgItem(ui.w,MINING_ON),SW_SHOW);ShowWindow(GetDlgItem(ui.w,MINING_OFF),SW_SHOW);}
 if(!ready)strcpy(sync,"Starting Core...");else if(!s.network.chain_connected)strcpy(sync,"Disconnected");else if(s.network.peer_current)snprintf(sync,sizeof(sync),"Synchronized   |   Height %s",h);else snprintf(sync,sizeof(sync),"Synchronizing   |   Height %s",h);SetWindowTextA(ui.sync,sync);ShowWindow(ui.progress,ready&&s.network.chain_connected&&!s.network.peer_current?SW_SHOW:SW_HIDE);SendMessage(ui.progress,PBM_SETMARQUEE,TRUE,0);}
static LRESULT CALLBACK proc(HWND w,UINT m,WPARAM wp,LPARAM lp){(void)lp;switch(m){case WM_COMMAND:switch(LOWORD(wp)){case B_OVERVIEW:page(P_OVERVIEW);break;case B_SEND:page(P_SEND);break;case B_RECEIVE:page(P_RECEIVE);break;case B_WALLET:page(P_WALLET);break;case B_CONTRACTS:page(P_CONTRACTS);break;case B_ACTIVITY:page(P_ACTIVITY);break;case CREATE_WALLET:queue(STNC_CLIENT_CREATE_WALLET);break;case CREATE_IDENTITY:queue(STNC_CLIENT_CREATE_IDENTITY);break;case SEND_NOW:send_now();break;case COPY_ADDRESS:copy_address();break;case MINING_ON:queue(STNC_CLIENT_MINING_ON);break;case MINING_OFF:queue(STNC_CLIENT_MINING_OFF);break;}return 0;case UPDATED:render();return 0;case STOPPED:if(ui.stopping)DestroyWindow(w);return 0;case WM_CLOSE:InterlockedExchange(&ui.stopping,1);SetEvent(ui.wake);return 0;case WM_DESTROY:PostQuitMessage(0);return 0;default:return DefWindowProcA(w,m,wp,lp);}}
int stnc_gui_bitcoin_run(void){WNDCLASSA c;MSG msg;INITCOMMONCONTROLSEX ic;int i;const char *names[]={"Overview","Send","Receive","Wallet","Contracts","Activity"};int ids[]={B_OVERVIEW,B_SEND,B_RECEIVE,B_WALLET,B_CONTRACTS,B_ACTIVITY};FreeConsole();memset(&ui,0,sizeof(ui));InitializeCriticalSection(&ui.lock);ui.wake=CreateEvent(0,FALSE,FALSE,0);ui.normal=CreateFontA(-16,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");ui.bold=CreateFontA(-18,0,0,0,FW_SEMIBOLD,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");ui.hero=CreateFontA(-26,0,0,0,FW_SEMIBOLD,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");ui.nav=CreateFontA(-15,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");ic.dwSize=sizeof(ic);ic.dwICC=ICC_PROGRESS_CLASS;InitCommonControlsEx(&ic);memset(&c,0,sizeof(c));c.lpfnWndProc=proc;c.hInstance=GetModuleHandle(0);c.lpszClassName="STNCCoreWindow";c.hCursor=LoadCursor(0,IDC_ARROW);c.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassA(&c);ui.w=CreateWindowExA(0,c.lpszClassName,"STNC Core",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX,CW_USEDEFAULT,CW_USEDEFAULT,900,620,0,0,c.hInstance,0);if(!ui.w)return 1;center(ui.w,900,620);for(i=0;i<6;++i){ui.buttons[i]=ctl("BUTTON",names[i],BS_FLAT|BS_PUSHBUTTON,ids[i],18+i*115,14,108,36);SendMessage(ui.buttons[i],WM_SETFONT,(WPARAM)ui.nav,TRUE);}ctl("BUTTON","Settings",BS_FLAT|BS_PUSHBUTTON,MINING_ON+100,708,14,108,36);ui.title=ctl("STATIC","Overview",0,0,34,72,810,34);SendMessage(ui.title,WM_SETFONT,(WPARAM)ui.hero,TRUE);ui.content=ctl("STATIC","Starting Core...",SS_LEFT,0,34,116,810,365);ui.sync=ctl("STATIC","Starting Core...",0,0,18,535,300,22);ui.progress=ctl(PROGRESS_CLASSA,"",PBS_MARQUEE,0,330,538,540,16);ctl("EDIT","",ES_AUTOHSCROLL|WS_BORDER,DESTINATION,170,220,590,26);ctl("EDIT","",ES_AUTOHSCROLL|WS_BORDER,AMOUNT,170,278,180,26);ctl("BUTTON","Send",BS_PUSHBUTTON,SEND_NOW,650,326,110,32);ctl("BUTTON","Copy address",BS_PUSHBUTTON,COPY_ADDRESS,650,245,130,32);ctl("BUTTON","Create wallet",BS_PUSHBUTTON,CREATE_WALLET,610,310,140,32);ctl("BUTTON","Create identity",BS_PUSHBUTTON,CREATE_IDENTITY,610,350,140,32);ctl("BUTTON","Start mining",BS_PUSHBUTTON,MINING_ON,560,330,120,32);ctl("BUTTON","Stop mining",BS_PUSHBUTTON,MINING_OFF,690,330,120,32);hide_actions();ShowWindow(ui.w,SW_SHOW);UpdateWindow(ui.w);ui.thread=CreateThread(0,0,runtime,0,0,0);while(GetMessage(&msg,0,0,0)>0){TranslateMessage(&msg);DispatchMessage(&msg);}WaitForSingleObject(ui.thread,INFINITE);CloseHandle(ui.thread);CloseHandle(ui.wake);DeleteCriticalSection(&ui.lock);return 0;}
